# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='q_txt_stuff',
        ),
    ]
