# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170817_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q_txt_stuff',
            new_name='question_text',
        ),
    ]
